title: Persistence of Vision Display
description: 30 FPS, full RGB color, and 26" diameter. Updates remotely over WIFI.
google_analytics: 
show_downloads: true
theme: jsut-the-docs

gems:
  - jekyll-mentions

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template