title: Persistence of Vision Display
description: 30 FPS, full RGB color, and 26" diameter. Updates remotely over WIFI.
theme: just-the-docs

url: https://usedhondacivic.github.io/ECE-4760-final-project