M48
; DRILL file {KiCad (6.0.6)} date Wed Nov  9 14:25:13 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-09T14:25:13-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X83.681Y-114.412
X88.531Y-114.412
T2
X83.381Y-111.382
X88.831Y-111.382
T0
M30
