M48
; DRILL file {KiCad (6.0.6)} date Thu Nov 10 16:32:21 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-10T16:32:21-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
%
G90
G05
T1
X90.733Y-58.77
X90.733Y-61.31
X90.733Y-63.85
X90.733Y-66.39
T0
M30
