M48
; DRILL file {KiCad (6.0.6)} date Tue Nov  8 17:29:09 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-08T17:29:09-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
%
G90
G05
T1
X84.582Y-58.684
X84.582Y-61.224
X84.582Y-63.764
X84.582Y-66.304
T0
M30
