M48
; DRILL file {KiCad (6.0.6)} date Tue Nov  8 17:00:44 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-08T17:00:44-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X51.931Y-107.554
X56.781Y-107.554
T2
X51.631Y-104.524
X57.081Y-104.524
T0
M30
